In [ ]:
import pandas as pd 
df= pd.read_csv("../input/atus_anual_2020.csv")
df.head()

In [ ]:
import pandas as pd 
df= pd.read_csv("../input/atus_anual_2021.csv")
df.head()

In [ ]:
import pandas as pd 
df= pd.read_csv("../input/atus_anual_2022.csv")
df.head()

In [22]:
import pandas as pd #1

df_2020 = pd.read_csv('../input/atus_anual_2020.csv', index_col=False)
df_2021 = pd.read_csv('../input/atus_anual_2021.csv',index_col=False)
df_2022 = pd.read_csv('../input/atus_anual_2022.csv',index_col=False)


df = pd.concat([df_2020, df_2021, df_2022], ignore_index=True)



df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067071 entries, 0 to 1067070
Data columns (total 45 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   COBERTURA     1067071 non-null  object
 1   ID_ENTIDAD    1067071 non-null  int64
 2   ID_MUNICIPIO  1067071 non-null  int64
 3   ANIO          1067071 non-null  int64
 4   MES           1067071 non-null  int64
 5   ID_HORA       1067071 non-null  int64
 6   ID_MINUTO     1067071 non-null  int64
 7   ID_DIA        1067071 non-null  int64
 8   DIASEMANA     1067071 non-null  object
 9   URBANA        1067071 non-null  object
 10  SUBURBANA     1067071 non-null  object
 11  TIPACCID      1067071 non-null  object
 12  AUTOMOVIL     1067071 non-null  int64
 13  CAMPASAJ      1067071 non-null  int64
 14  MICROBUS      1067071 non-null  int64
 15  PASCAMION     1067071 non-null  int64
 16  OMNIBUS       1067071 non-null  int64
 17  TRANVIA       1067071 non-null  int64
 18  CAMIONETA     1067071 non-null  int64
 19  CAMION        1067071 non-null  int64
 20  TRACTOR       1067071 non-null  int64
 21  FERROCARRI    1067071 non-null  int64
 22  MOTOCICLET    1067071 non-null  int64
 23  BICICLETA     1067071 non-null  int64
 24  OTROVEHIC     1067071 non-null  int64
 25  CAUSAACCI     1067071 non-null  object
 26  CAPAROD       1067071 non-null  object
 27  SEXO          1067071 non-null  object
 28  ALIENTO       1067071 non-null  object
 29  CINTURON      1067071 non-null  object
 30  ID_EDAD       1067071 non-null  int64
 31  CONDMUERTO    1067071 non-null  int64
 32  CONDHERIDO    1067071 non-null  int64
 33  PASAMUERTO    1067071 non-null  int64
 34  PASAHERIDO    1067071 non-null  int64
 35  PEATMUERTO    1067071 non-null  int64
 36  PEATHERIDO    1067071 non-null  int64
 37  CICLMUERTO    1067071 non-null  int64
 38  CICLHERIDO    1067071 non-null  int64
 39  OTROMUERTO    1067071 non-null  int64
 40  OTROHERIDO    1067071 non-null  int64
 41  NEMUERTO      1067071 non-null  int64
 42  NEHERIDO      1067071 non-null  int64
 43  CLASACC       1067071 non-null  object
 44  ESTATUS       1067071 non-null  object
dtypes: int64(33), object(12)
memory usage: 366.3+ MB

In [38]:
#2
df['FECHA'] = df.apply(lambda row: f"{row['ANIO']}-{row['MES']}-{row['ID_DIA']} {row['ID_HORA']}:{row['ID_MINUTO']}", axis=1)
df['FECHA'] = pd.to_datetime(df['FECHA'], format='%Y-%m-%d %H:%M')

print(df.head())

   COBERTURA  ID_ENTIDAD  ID_MUNICIPIO  ANIO  MES  ID_HORA  ID_MINUTO  ID_DIA  \
0  Municipal           1             1  2020    1        0          0       1
1  Municipal           1             1  2020    1        0          0       1
2  Municipal           1             1  2020    1        0         10       1
3  Municipal           1             1  2020    1        2          0       1
4  Municipal           1             1  2020    1        2         10       1

   DIASEMANA                     URBANA  ... OTROMUERTO OTROHERIDO  NEMUERTO  \
0  Miercoles  Accidente en intersección  ...          0          0         0
1  Miercoles  Accidente en intersección  ...          0          0         0
2  Miercoles  Accidente en intersección  ...          0          0         0
3  Miercoles  Accidente en intersección  ...          0          0         0
4  Miercoles  Accidente en intersección  ...          0          0         0

   NEHERIDO     CLASACC             ESTATUS    AREA  \
0         0  Sólo daños  Cifras Definitivas  URBANA
1         0  Sólo daños  Cifras Definitivas  URBANA
2         0  Sólo daños  Cifras Definitivas  URBANA
3         0  Sólo daños  Cifras Definitivas  URBANA
4         0  Sólo daños  Cifras Definitivas  URBANA

                        ZONA  AccidentesPorMes               FECHA
0  Accidente en intersección               NaN 2020-01-01 00:00:00
1  Accidente en intersección               NaN 2020-01-01 00:00:00
2  Accidente en intersección               NaN 2020-01-01 00:10:00
3  Accidente en intersección               NaN 2020-01-01 02:00:00
4  Accidente en intersección               NaN 2020-01-01 02:10:00

[5 rows x 49 columns]

In [28]:
#3
def detArea(row):
    if row['SUBURBANA'] != 'Sin accidente en esta zona':
        return 'SUBURBANA'
    else:
        return 'URBANA'


df['AREA']= df.apply(detArea,axis=1)

df[df['AREA']=='SUBURBANA']

,COBERTURA,ID_ENTIDAD,ID_MUNICIPIO,ANIO,MES,ID_HORA,ID_MINUTO,ID_DIA,DIASEMANA,URBANA,...,CICLMUERTO,CICLHERIDO,OTROMUERTO,OTROHERIDO,NEMUERTO,NEHERIDO,CLASACC,ESTATUS,AREA,ZONA
98,Municipal,1,1,2020,1,20,33,11,Sabado,Sin accidente en esta zona,...,0,0,0,0,0,0,No fatal,Cifras Definitivas,SUBURBANA,Accidente en carretera estatal
119,Municipal,1,1,2020,1,12,13,13,lunes,Sin accidente en esta zona,...,0,0,0,0,0,0,No fatal,Cifras Definitivas,SUBURBANA,Accidente en carretera estatal
345,Municipal,1,1,2020,2,19,32,9,Domingo,Sin accidente en esta zona,...,0,0,0,0,0,0,Sólo daños,Cifras Definitivas,SUBURBANA,Accidente en carretera estatal
358,Municipal,1,1,2020,2,11,0,11,Martes,Sin accidente en esta zona,...,0,0,0,0,0,0,No fatal,Cifras Definitivas,SUBURBANA,Accidente en camino rural
409,Municipal,1,1,2020,2,8,20,16,Domingo,Sin accidente en esta zona,...,0,0,0,0,0,0,Sólo daños,Cifras Definitivas,SUBURBANA,Accidente en carretera estatal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1066497,Municipal,32,55,2022,11,18,13,13,Domingo,Sin accidente en esta zona,...,0,0,0,0,0,0,No fatal,Cifras Definitivas,SUBURBANA,Accidente en carretera estatal
1066499,Municipal,32,55,2022,11,20,0,27,Domingo,Sin accidente en esta zona,...,0,0,0,0,0,0,No fatal,Cifras Definitivas,SUBURBANA,Accidente en carretera estatal
1066500,Municipal,32,55,2022,12,0,0,1,Jueves,Sin accidente en esta zona,...,0,0,0,0,0,0,Fatal,Cifras Definitivas,SUBURBANA,Accidente en camino rural
1066501,Municipal,32,55,2022,12,15,10,1,Jueves,Sin accidente en esta zona,...,0,0,0,0,0,0,No fatal,Cifras Definitivas,SUBURBANA,Accidente en carretera estatal
1066505,Municipal,32,55,2022,12,1,40,28,Miercoles,Sin accidente en esta zona,...,0,0,0,0,0,0,Sólo daños,Cifras Definitivas,SUBURBANA,Accidente en camino rural

In [24]:
#4
def detZona(row):
    if row['AREA']=='URBANA':
        return row['URBANA']
    else:
         return row['SUBURBANA']

df['ZONA']= df.apply(detZona,axis=1)
print(df)

         COBERTURA  ID_ENTIDAD  ID_MUNICIPIO  ANIO  MES  ID_HORA  ID_MINUTO  \
0        Municipal           1             1  2020    1        0          0
1        Municipal           1             1  2020    1        0          0
2        Municipal           1             1  2020    1        0         10
3        Municipal           1             1  2020    1        2          0
4        Municipal           1             1  2020    1        2         10
...            ...         ...           ...   ...  ...      ...        ...
1067066  Municipal          32            56  2022   12        7         45
1067067  Municipal          32            56  2022   12        8          0
1067068  Municipal          32            56  2022   12       17         20
1067069  Municipal          32            56  2022   12       14         45
1067070  Municipal          32            56  2022   12       22         15

         ID_DIA  DIASEMANA                     URBANA  ... CICLMUERTO  \
0             1  Miercoles  Accidente en intersección  ...          0
1             1  Miercoles  Accidente en intersección  ...          0
2             1  Miercoles  Accidente en intersección  ...          0
3             1  Miercoles  Accidente en intersección  ...          0
4             1  Miercoles  Accidente en intersección  ...          0
...         ...        ...                        ...  ...        ...
1067066      30    Viernes  Accidente en intersección  ...          0
1067067      30    Viernes  Accidente en intersección  ...          0
1067068      30    Viernes  Accidente en intersección  ...          0
1067069      31     Sabado  Accidente en intersección  ...          0
1067070      31     Sabado  Accidente en intersección  ...          0

        CICLHERIDO  OTROMUERTO  OTROHERIDO  NEMUERTO  NEHERIDO     CLASACC  \
0                0           0           0         0         0  Sólo daños
1                0           0           0         0         0  Sólo daños
2                0           0           0         0         0  Sólo daños
3                0           0           0         0         0  Sólo daños
4                0           0           0         0         0  Sólo daños
...            ...         ...         ...       ...       ...         ...
1067066          0           0           0         0         0    No fatal
1067067          0           0           0         0         0  Sólo daños
1067068          0           0           0         0         0  Sólo daños
1067069          0           0           0         0         0  Sólo daños
1067070          0           0           0         0         0  Sólo daños

                    ESTATUS    AREA                       ZONA
0        Cifras Definitivas  URBANA  Accidente en intersección
1        Cifras Definitivas  URBANA  Accidente en intersección
2        Cifras Definitivas  URBANA  Accidente en intersección
3        Cifras Definitivas  URBANA  Accidente en intersección
4        Cifras Definitivas  URBANA  Accidente en intersección
...                     ...     ...                        ...
1067066  Cifras Definitivas  URBANA  Accidente en intersección
1067067  Cifras Definitivas  URBANA  Accidente en intersección
1067068  Cifras Definitivas  URBANA  Accidente en intersección
1067069  Cifras Definitivas  URBANA  Accidente en intersección
1067070  Cifras Definitivas  URBANA  Accidente en intersección

[1067071 rows x 47 columns]

In [20]:
#5

df.drop(columns=['URBANA', 'SUBURBANA'], inplace=True)
print(df.head())

   COBERTURA  ID_ENTIDAD  ID_MUNICIPIO  ANIO  MES  ID_HORA  ID_MINUTO  ID_DIA  \
0  Municipal           1             1  2020    1        0          0       1
1  Municipal           1             1  2020    1        0          0       1
2  Municipal           1             1  2020    1        0         10       1
3  Municipal           1             1  2020    1        2          0       1
4  Municipal           1             1  2020    1        2         10       1

   DIASEMANA                         TIPACCID  ...  PEATMUERTO  PEATHERIDO  \
0  Miercoles  Colisión con vehículo automotor  ...           0           0
1  Miercoles         Colisión con objeto fijo  ...           0           0
2  Miercoles         Colisión con motocicleta  ...           0           0
3  Miercoles  Colisión con vehículo automotor  ...           0           0
4  Miercoles  Colisión con vehículo automotor  ...           0           0

   CICLMUERTO  CICLHERIDO  OTROMUERTO  OTROHERIDO  NEMUERTO  NEHERIDO  \
0           0           0           0           0         0         0
1           0           0           0           0         0         0
2           0           0           0           0         0         0
3           0           0           0           0         0         0
4           0           0           0           0         0         0

      CLASACC             ESTATUS
0  Sólo daños  Cifras Definitivas
1  Sólo daños  Cifras Definitivas
2  Sólo daños  Cifras Definitivas
3  Sólo daños  Cifras Definitivas
4  Sólo daños  Cifras Definitivas

[5 rows x 43 columns]

In [34]:
#6
df['AccidentesPorMes'] = df[['AUTOMOVIL', 'CAMPASAJ', 'MICROBUS', 'PASCAMION', 'OMNIBUS', 'TRANVIA',
                                       'CAMIONETA', 'CAMION', 'TRACTOR', 'FERROCARRI', 'MOTOCICLET', 'BICICLETA',
                                       'OTROVEHIC']].sum() 
accidentes=df.groupby(['ID_ENTIDAD','ID_MUNICIPIO','ANIO'])['MES'].value_counts().reset_index() 
accidentesMes = accidentes.loc[accidentes.groupby('ID_ENTIDAD')['count'].idxmin()]
accidentesMes.sort_index() 
accidentesMes

       ID_ENTIDAD  ID_MUNICIPIO  ANIO  MES  count
46              1             2  2020    3      1
503             2             3  2022    8      5
623             3             2  2020    9      1
767             4             1  2020    6      1
1176            5             1  2020    1      1
2729            6             6  2020    2      1
2904            7             1  2020    1      1
7294            8             1  2020    7      1
9191            9             8  2022    7      2
9552           10             3  2020    6      1
10633          11             6  2020    1      1
12145          12             2  2020    1      1
14854          13             1  2020    1      1
17919          14             2  2020    4      1
22379          15             1  2020    2      1
24281          16             1  2020    2      1
28317          17             1  2020    3      1
29590          18             1  2020    1      1
30264          19             1  2020    1      1
32098          20             1  2020    1      1
52618          21             1  2020    1      1
60477          22             2  2020    4      1
61159          23             3  2020    4      2
61474          24             1  2020    1      1
63609          25             2  2020   11      1
64210          26             1  2020    1      1
66811          27             1  2020    3      1
67416          28             1  2020    1      1
68962          29             1  2020    1      1
71122          30             1  2020    1      1
78764          31             2  2020    5      1
80770          32             1  2022   10      1

In [36]:
#7
tipo_accidente_counts = df_2022['TIPACCID'].value_counts().reset_index()
tipo_accidente_counts.columns = ['Tipo de Accidente', 'Count']

total_accidentes = tipo_accidente_counts['Count'].sum()
tipo_accidente_counts['Porcentaje sobre el Total'] = (tipo_accidente_counts['Count'] / total_accidentes) * 100
print(tipo_accidente_counts)

                        Tipo de Accidente   Count  Porcentaje sobre el Total
0         Colisión con vehículo automotor  229940                  58.552112
1                Colisión con motocicleta   53629                  13.656133
2                Colisión con objeto fijo   47033                  11.976522
3                        Certificado cero   15479                   3.941585
4   Colisión con peatón (atropellamiento)   11066                   2.817855
5                               Volcadura   10911                   2.778386
6                       Salida del camino   10857                   2.764635
7                                    Otro    6325                   1.610603
8                   Colisión con ciclista    4048                   1.030786
9                       Caída de pasajero    1784                   0.454279
10                    Colisión con animal    1022                   0.260243
11                               Incendio     348                   0.088615
12               Colisión con ferrocarril     268                   0.068244

In [35]:
#8

total_muertos = df['PEATMUERTO'].sum()+df['CICLMUERTO'].sum()+df['OTROMUERTO'].sum()+df['NEMUERTO'].sum()
total_lesionados =df['PEATHERIDO'].sum()+df['CICLHERIDO'].sum()+df['OTROHERIDO'].sum()+df['NEHERIDO'].sum()

print("Cantidad de muertos en los últimos 3 años:", total_muertos)
print("Cantidad de heridos en los últimos 3 años:", total_lesionados)

Cantidad de muertos en los últimos 3 años: 3270
Cantidad de heridos en los últimos 3 años: 39686

In [39]:
#9
df['FECHA'] = pd.to_datetime(df['FECHA'])


df['AÑO'] = df['FECHA'].dt.year


total_accidentes_por_año = df['AÑO'].value_counts().reset_index()
total_accidentes_por_año.columns = ['AÑO', 'Total_Accidentes']

total_accidentes_por_año['Porcentaje'] = (total_accidentes_por_año['Total_Accidentes'] / total_accidentes_por_año['Total_Accidentes'].sum()) * 100

datos = df.drop('AÑO', axis = 1)
print(total_accidentes_por_año)

    AÑO  Total_Accidentes  Porcentaje
0  2022            392710   36.802612
1  2021            356315   33.391874
2  2020            318046   29.805514